### ISSUE TITLE
Advantages over hoyon/mpv-mpris

### ISSUE THREAD

**Issue by danielwerg** [eNV25/mpv-mpris2#71]
Didn't see anything in readme, is there a reason to use this over hoyon/mpv-mpris?

Also why is this not in aur? https://github.com/eNV25/pkgs/blob/master/mpv-mpris2/PKGBUILD

**Comment by eNV25** [comment]
I'm currently not working this actively, because I don't like this implementation and I'm not completely satisfied with the code. I'm currently working a version with C++ and QtCore. I'll finish it and release it next month after I'm finished with Advent of Code 2024.

One advantage is that it doesn't require any system libraries, like glib2 or QtCore.

**Comment by shmerl** [comment]
Is this still the case? There were some recent commits. Are you working on improving it or you recommend using something else?

**Comment by eNV25** [comment]
You can still use it. It works. I just won't make big changes, I'm busy with school.
